<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260716111303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timezone VARCHAR(64) NOT NULL, locale VARCHAR(16) NOT NULL, date_format VARCHAR(32) NOT NULL, time_format VARCHAR(32) NOT NULL, first_day_of_week INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA0E76BFA76ED395 ON user_preference (user_id)');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_FA0E76BFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_FA0E76BFA76ED395');
        $this->addSql('DROP TABLE user_preference');
    }
}
