<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260725130431 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE calendar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, timezone VARCHAR(100) NOT NULL, visible BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, is_read_only BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EA9A1469033212A ON calendar (tenant_id)');
        $this->addSql('CREATE INDEX IDX_6EA9A1467E3C61F9 ON calendar (owner_id)');
        $this->addSql('CREATE TABLE calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, all_day BOOLEAN NOT NULL, external_id VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, calendar_id INT NOT NULL, organization_id INT DEFAULT NULL, assigned_to_id INT DEFAULT NULL, dossier_id INT DEFAULT NULL, staff_member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57FA09C9A40A2C8 ON calendar_event (calendar_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C932C8A3DE ON calendar_event (organization_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C9F4BD7827 ON calendar_event (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C9611C0C56 ON calendar_event (dossier_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C944DB03B1 ON calendar_event (staff_member_id)');
        $this->addSql('CREATE INDEX IDX_57FA09C9B75363F737D3107C ON calendar_event (start_at, end_at)');
        $this->addSql('CREATE TABLE dossier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D48E03732C8A3DE ON dossier (organization_id)');
        $this->addSql('CREATE TABLE kanban_board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, position INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AA902B95989D9B62 ON kanban_board (slug)');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1EE637C9033212A ON organization (tenant_id)');
        $this->addSql('CREATE INDEX IDX_C1EE637C9033212A5E237E06 ON organization (tenant_id, name)');
        $this->addSql('CREATE TABLE organization_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, staff_member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_756A2A8D32C8A3DE ON organization_member (organization_id)');
        $this->addSql('CREATE INDEX IDX_756A2A8D44DB03B1 ON organization_member (staff_member_id)');
        $this->addSql('CREATE INDEX IDX_756A2A8D32C8A3DE44DB03B1 ON organization_member (organization_id, staff_member_id)');
        $this->addSql('CREATE TABLE staff_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, active BOOLEAN NOT NULL, calendar_color VARCHAR(7) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_759948C39033212A ON staff_member (tenant_id)');
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, slug VARCHAR(150) NOT NULL, logo VARCHAR(255) DEFAULT NULL, primary_color VARCHAR(7) NOT NULL, secondary_color VARCHAR(7) NOT NULL, website VARCHAR(255) DEFAULT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(30) DEFAULT NULL, timezone VARCHAR(100) NOT NULL, locale VARCHAR(10) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E59C4625E237E06 ON tenant (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E59C46277153098 ON tenant (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E59C462989D9B62 ON tenant (slug)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timezone VARCHAR(64) NOT NULL, locale VARCHAR(10) NOT NULL, first_day_of_week INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA0E76BFA76ED395 ON user_preference (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A1469033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A1467E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C944DB03B1 FOREIGN KEY (staff_member_id) REFERENCES staff_member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E03732C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8D44DB03B1 FOREIGN KEY (staff_member_id) REFERENCES staff_member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE staff_member ADD CONSTRAINT FK_759948C39033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_FA0E76BFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A1469033212A');
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A1467E3C61F9');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9A40A2C8');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C932C8A3DE');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9F4BD7827');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9611C0C56');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C944DB03B1');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E03732C8A3DE');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637C9033212A');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8D32C8A3DE');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8D44DB03B1');
        $this->addSql('ALTER TABLE staff_member DROP CONSTRAINT FK_759948C39033212A');
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_FA0E76BFA76ED395');
        $this->addSql('DROP TABLE calendar');
        $this->addSql('DROP TABLE calendar_event');
        $this->addSql('DROP TABLE dossier');
        $this->addSql('DROP TABLE kanban_board');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_member');
        $this->addSql('DROP TABLE staff_member');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_preference');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
